# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/phy/cert_test:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s2", "esp32s3"]
      temporary: true
      reason: the other targets are not tested yet
